export const FETCH_MOVIES = "fetch_movies";

export const FETCH_MOVIES_BEGIN = "FETCH_MOVIES_BEGIN";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE";

export const CHANGE_PAGE = "CHANGE_PAGE";

export const FETCH_CAST_BEGIN = "FETCH_CAST_BEGIN";
export const FETCH_CAST_SUCCESS = "FETCH_CAST_SUCCESS";
export const FETCH_CAST_FAILURE = "FETCH_CAST_FAILURE";

export const FETCH_SIMILAR_BEGIN = "FETCH_SIMILAR_BEGIN";
export const FETCH_SIMILAR_SUCCESS = "FETCH_SIMILAR_SUCCESS";
export const FETCH_SIMILAR_FAILURE = "FETCH_SIMILAR_FAILURE";

export const FETCH_RECOMMENDATION_BEGIN = "FETCH_RECOMMENDATION_BEGIN";
export const FETCH_RECOMMENDATION_SUCCESS = "FETCH_RECOMMENDATION_SUCCESS";
export const FETCH_RECOMMENDATION_FAILURE = "FETCH_RECOMMENDATION_FAILURE";

export const FETCH_REVIEWS_BEGIN = "FETCH_REVIEWS_BEGIN";
export const FETCH_REVIEWS_SUCCESS = "FETCH_REVIEWS_SUCCESS";
export const FETCH_REVIEWS_FAILURE = "FETCH_REVIEWS_FAILURE";
